// Canonical subcategory names per category, copied verbatim from
// Categories.md (the authoritative source — see the project root). Shared
// between the one-time Subcategory backfill migration and `seed.ts` (so a
// fresh database seeds identically to a migrated one) — do not duplicate
// this list anywhere else.
//
// Handloom Pattu Saree's list has one exact duplicate in the source doc
// ("Gap Border Brahamini Saree" appears twice, items 43 and 64) — collapsed
// to a single subcategory here since Subcategory names are unique per
// category and the doc gives no way to distinguish the two entries.
export const SUBCATEGORIES_BY_CATEGORY_SLUG: Record<string, string[]> = {
  'handloom-pattu-saree': [
    'Double Zari lines',
    'Zute line Saree',
    '50/50 Real Bandini',
    'Temple Border Screenprint',
    '50/50 Middle checks Embroidery',
    'Gap Border Embroidery',
    'Scallop Embroidery',
    '250k Border Screen print',
    'Triple colour Rangoli Border',
    'Kanchi Border Chikankari Saree',
    'Scallop Zute line Saree Blouse',
    'Scallop Border Hand painted Saree',
    'Needle Shibori Saree',
    '150 Border Real Bandini & Ajrakh',
    '50/50 Digital print',
    '150/50 Digital print',
    '250/50 Digital print',
    '350/50 Digital print',
    'Flower Scallop Border',
    '150/50 Screenprint dye',
    '50/50 Kalamkari Saree',
    'Pure Pattu Chikankari Saree',
    '200k Hand Painted Saree',
    'Gap Border Digital Print Saree',
    '250k Butta Saree',
    '350k Butta Saree',
    'Gap Border Real Tanjore Hand Painted Saree',
    '50/50 Tanjore Screen Print Saree',
    'Gap Border Kalamkari Saree',
    '50/50 Middle Checks Screen Printed Saree',
    '50/50 Zute Line Saree',
    'Scallop Kollam & Design Printed Saree',
    'Scallop Flower Bunch Applique Saree',
    'Plain Ikkath Screen Printed Saree',
    '50/50 Embroidery',
    '150/50 Embroidery',
    '100/50 Chikankari Saree',
    '250/50 Embroidery',
    '50/50 Middle Checks Hand Painted Saree',
    '200k Rudraksha Plain Saree',
    'Gap Border Kalamkari Patchwork Saree',
    'Scallop Real Bandini Saree',
    'Gap Border Brahamini Saree',
    '200k Checks Saree',
    'Plain Patch Work Saree',
    'Scallop Screen Printed Saree',
    'Scallop Dye Maggam Work Saree',
    'Tissue Border Straight Line Saree',
    'Pure Pattu 250k Butta Saree',
    'Pure Pattu 350k Butta Saree',
    'Scallop Digital Print Saree',
    '300k Ikkath Border Check Saree',
    'Pure 250k Checks Saree',
    'Pure 350k Checks Saree',
    '250k Tanjore Sticker Saree',
    'Pure 400k border Saree',
    'Pure Pattu/Pattu Ikkath Design Saree',
    'Pure Pattu/Pure Samudrika Pattu Saree',
    '50/50 Screen Printed Saree',
    '50/50 Embossing Screen Printed Saree',
    'Pure Pattu Real Srikalahasthi Pen Kalamkari Saree',
    'Kalamkari Pattu Saree',
    'Kadi Border Kalamkari Saree',
    '250k Checks Saree',
    'Scallop Zari Line Embroidery Blouse',
    '150/50 Ikkath Flower Bunch Saree',
    '50/50 Real Tanjore Printed Saree',
    '250k Plain Saree',
    '300k Plain Saree',
    'Scallop Mirror Work Saree',
    'Pure Small Border Screen Printed Saree',
    'Pure Big Border Screen Printed Saree',
    'Pure Small Border Plain Saree',
    'Pure Big Border Plain Saree',
    'Kanchi Border Triple Check Saree',
    'Gap Border Plain Saree',
    'Plain Shibori Saree',
    'Plain Shibori Bandini Saree',
    'Scallop Bandini Saree, Maggam Blouse',
    'Scallop Maggam Work Saree',
    '50/50 Double Check Saree',
    '50/50 Middle Check Saree',
    '50/50 Flower Bunch Applique',
    'Scallop Applique Saree',
    '50/50 Applique Saree',
    '150/50 Applique Saree',
    '50/50 Border Baguru Printed Saree — Border',
    'Single Peacock Plain Saree, Tanjore Blouse',
    'Scallop Real Ikkath Printed Saree',
    '50/50 Ikkath Saree',
    '50/50 Plain Saree',
    '150/50 Plain Saree',
    '200k Butta Saree',
    '400k Checks Saree',
    '400k Plain Saree',
    'Plain Saree Kalamkari Blouse',
    'Plain Saree Digital Blouse',
    '50/50 Kollam Embroidery Saree',
  ],
  'handloom-cotton-saree': [
    'Plain Cotton Saree',
    'Plain Cotton Straight Line Saree',
    'Cotton Checks Saree',
    'Plain Printed Cotton Saree',
    'Temple Border Plain Saree',
    'Gap Border Printed Saree',
    'Linen Cotton Printed',
    'Cotton Digital Printed',
    'Cotton Gap Border Saree',
    '50/50 Line Saree',
    'Cotton Embroidery Saree',
  ],
  'handloom-pattu-dress-material': [
    'Applique Work Dress Materials',
    'Real Tanjore Painted Dress Material',
    'Rangoli Border Block Printed',
    '50/50 Dress Material',
    '50/50 Zute Line Dress Material',
    '250k Top Digital Duppata',
    '250k Butta Top Digital Duppata',
    'Single Peacock Dress Material',
    '300k Hand Painted Dress Material',
    '300k Dye Screen Printed Material',
    '300k Shibori Dress Material',
    '50/50 Screen Printed Dress Material',
    'Digital Top / Digital Duppata Dress Material',
    'Dye Magam Work Dress Material',
    '250k Baguru Printed Dress Material',
    '250k Shibori Bandini Dress Material',
    '200k Checks Dress Material',
    '250k Screen Printed Top Plain Duppata',
    '250k Plain Top Screen Printed Duppata',
    '50/50 Chikankari Dress Material',
    'Gap Border Mangalagiri Kalamkari Dress Material',
    'Plain Top Real Srikalahasthi Duppata',
    'Applique Top Applique Duppata Dress',
    '250k Butta Dress Materials',
  ],
  'handloom-cotton-dress-material': [
    '50/50 Plain Dress Materials',
    'Temple Border Plain Dress Material',
    '50/50 Screen Printed Dress Materials',
    'Plain Embossing Print',
    'Gap Border Embossing Print',
    '50/50 Stripes Dress Materials',
  ],
  'pattu-lehanga-sets': [
    'Full Digital Set Lehanga',
    'Kalamkari Lehanga Sets',
    '250k Lehanga Sets',
    '250k kutch Work Embroidery Lehanga',
    '300k ikkath Border Lehanga Sets',
    '350k Hand Painted Lehanga Set',
    '350k Plain Lehanga Digital Voni',
    '350k Plain Lehanga Scallop Pen Kalamkari Voni',
    '350k Checks Digital Lehanga Voni',
    '350k Butta Lehanga Scallop Pen Kalamkari Voni',
    'Gap Border Applique Work Lehanga Sets',
  ],
  // Fabrics deliberately has no subcategories yet — admin adds them as
  // stock arrives, same as the other categories did before Categories.md.
  fabrics: [],
};
